Alfresco/alfresco-sdk

README.md

Here is the first take on an Updated SDK Readme

Updated SDK README

---

archetypes/alfresco-allinone-archetype/pom.xml

Suggested from the Community.
(thank you Digicat and Yreg)

Typo in description.

---

archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/README.md
archetypes/alfresco-platform-jar-archetype/src/main/resources/archetype-resources/README.md
archetypes/alfresco-share-jar-archetype/src/main/resources/archetype-resources/README.md
pom.xml

Update the README files of the archetypes with the new approach of the
Alfresco SDK.

Archetypes - Update README files

---

archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/docker/docker-compose.yml
archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/run.bat
archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/run.sh
archetypes/alfresco-platform-jar-archetype/src/main/resources/archetype-resources/docker/docker-compose.yml
archetypes/alfresco-platform-jar-archetype/src/main/resources/archetype-resources/run.bat
archetypes/alfresco-platform-jar-archetype/src/main/resources/archetype-resources/run.sh
archetypes/alfresco-share-jar-archetype/src/main/resources/archetype-resources/docker/docker-compose.yml
archetypes/alfresco-share-jar-archetype/src/main/resources/archetype-resources/run.bat
archetypes/alfresco-share-jar-archetype/src/main/resources/archetype-resources/run.sh

- Remove needless messages from the run scripts.
- Change postgresql log level to avoid showing unnecessary messages.

Archetypes - Logging improvements

---

plugins/alfresco-maven-plugin/src/main/java/org/alfresco/maven/plugin/AbstractRunMojo.java

Modify the Alfresco Maven Plugin in order to take into
account the order in which the AMP modules were defined
as the same order of the AMPs to be applied to the war
files.
#469

BUGFIX - 469 - Maven Plugin - AMP files order

---

archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/pom.xml
archetypes/alfresco-platform-jar-archetype/src/main/resources/archetype-resources/pom.xml
archetypes/alfresco-share-jar-archetype/src/main/resources/archetype-resources/pom.xml

Modify the pom.xml files of the archetypes to include the
yuicompressor-maven-plugin in order to configure the minification
of the JS files.
#255 
#423

BUGFIX - 255 - Archetypes - Add JS minification

---

archetypes/alfresco-allinone-archetype/pom.xml
archetypes/alfresco-allinone-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml
archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/.gitignore
archetypes/alfresco-platform-jar-archetype/pom.xml
archetypes/alfresco-platform-jar-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml
archetypes/alfresco-platform-jar-archetype/src/main/resources/archetype-resources/.gitignore
archetypes/alfresco-share-jar-archetype/pom.xml
archetypes/alfresco-share-jar-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml
archetypes/alfresco-share-jar-archetype/src/main/resources/archetype-resources/.gitignore

Add standard gitignore files to the archetypes.

Archetypes - Add gitignore files to archetypes

---

archetypes/alfresco-platform-jar-archetype/src/main/resources/archetype-resources/pom.xml
archetypes/alfresco-platform-jar-archetype/src/main/resources/archetype-resources/src/test/java/platformsample/CustomContentModelIT.java
archetypes/alfresco-platform-jar-archetype/src/main/resources/archetype-resources/src/test/java/platformsample/DemoComponentIT.java
archetypes/alfresco-platform-jar-archetype/src/main/resources/archetype-resources/src/test/java/platformsample/HelloWorldWebScriptIT.java
archetypes/archetypes-it/src/test/java/org/alfresco/maven/archetype/PlatformJarArchetypeIT.java

Modify the platform JAR archetype to include sample ITs.

Archetypes - Add ITs to platform jar archetype

---

docs/advanced-topics/upgrading.md

This PR adds a new file called upgrading.md that documents the steps necessary to upgrade from 3.0.1 to 4.0.0.

Steps to upgrade to 4.0

---

archetypes/alfresco-share-jar-archetype/src/main/resources/archetype-resources/README.md
archetypes/alfresco-share-jar-archetype/src/main/resources/archetype-resources/pom.xml
archetypes/alfresco-share-jar-archetype/src/main/resources/archetype-resources/run.bat
archetypes/alfresco-share-jar-archetype/src/main/resources/archetype-resources/run.sh

- Build the project using package goal instead of install
- Remove unused test tasks of the scripts

Archetypes - Change share archetype build approach

---

archetypes/activiti-jar-archetype/pom.xml
archetypes/alfresco-allinone-archetype/pom.xml
archetypes/alfresco-platform-jar-archetype/pom.xml
archetypes/alfresco-share-jar-archetype/pom.xml
modules/alfresco-rad/pom.xml
plugins/alfresco-maven-plugin/pom.xml
pom.xml

SDK 3.1 RELEASE

---

archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/run.sh
archetypes/alfresco-platform-jar-archetype/src/main/resources/archetype-resources/run.sh
archetypes/alfresco-share-jar-archetype/src/main/resources/archetype-resources/run.sh

The script fails if the working directory contains whitespaces

Allow working directory to include whitespaces

---

archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/__rootArtifactId__-platform/src/main/resources/alfresco/module/__artifactId__/context/bootstrap-context.xml
archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/__rootArtifactId__-platform/src/main/resources/alfresco/module/__artifactId__/messages/workflow-messages.properties
archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/__rootArtifactId__-platform/src/main/resources/alfresco/module/__artifactId__/workflow/sample-process.bpmn20.xml
archetypes/alfresco-platform-jar-archetype/src/main/resources/archetype-resources/src/main/resources/alfresco/module/__artifactId__/context/bootstrap-context.xml
archetypes/alfresco-platform-jar-archetype/src/main/resources/archetype-resources/src/main/resources/alfresco/module/__artifactId__/messages/workflow-messages.properties
archetypes/alfresco-platform-jar-archetype/src/main/resources/archetype-resources/src/main/resources/alfresco/module/__artifactId__/workflow/sample-process.bpmn20.xml

Fix workflow sample in aio and platform archetypes

Archetypes - Fix workflow sample

---

docs/advanced-topics/amps.md

Added to amps.doc  - how to pull local AMP into project, have local amp be used in/by docker

Mwallach amp docs

---

archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/docker/docker-compose.yml
archetypes/alfresco-platform-jar-archetype/src/main/resources/archetype-resources/docker/docker-compose.yml
archetypes/alfresco-share-jar-archetype/src/main/resources/archetype-resources/docker/docker-compose.yml
docs/working-with-generated-projects/working-with-aio.md
docs/working-with-generated-projects/working-with-platform.md
docs/working-with-generated-projects/working-with-share.md

The Search Services is now using anew default "secret" communication method.
The changes also have updates to the latest Search Services version (2.0.3)

REPO-5711 Fix repository to Search services comms

---

.github/workflows/ci.yml

Added missing failure & cancelled condition checks.

ACS-3750 Fix cancelled workflow condition

---

archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/pom.xml
archetypes/alfresco-platform-jar-archetype/src/main/resources/archetype-resources/pom.xml
archetypes/alfresco-share-jar-archetype/src/main/resources/archetype-resources/pom.xml

https://alfresco.atlassian.net/browse/MNT-23888

[MNT-23888] Changes done for handling reserved words while compressing the Javascript files.

---

plugins/alfresco-maven-plugin/pom.xml

https://hyland.atlassian.net/browse/PRODSEC-9046

[PRODSEC-9046] fix for sdk vulnerability

---

plugins/alfresco-maven-plugin/pom.xml

https://hyland.atlassian.net/browse/PRODSEC-9051

[PRODSEC-9051] fix plexus archiver

---

plugins/alfresco-maven-plugin/pom.xml

https://hyland.atlassian.net/browse/PRODSEC-9046

[PRODSEC-9046] Fix for alfresco-sdk security issues

---

plugins/alfresco-maven-plugin/pom.xml

https://hyland.atlassian.net/browse/PRODSEC-8959

[PRODSEC-8959] fix for zt-zip vulnerability

---

plugins/alfresco-maven-plugin/pom.xml

https://hyland.atlassian.net/browse/PRODSEC-9043

[PRODSEC-9043] fix for maven-core vulnerability

---

plugins/alfresco-maven-plugin/pom.xml

https://hyland.atlassian.net/browse/PRODSEC-8961

[PRODSEC-8961] fix for commons-net vulnerability

---

plugins/alfresco-maven-plugin/pom.xml

https://hyland.atlassian.net/browse/PRODSEC-9063

[PRODSEC-9063] fix for maven-shared-utils

---

archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/run.bat
archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/run.sh
archetypes/alfresco-platform-jar-archetype/src/main/resources/archetype-resources/run.bat
archetypes/alfresco-platform-jar-archetype/src/main/resources/archetype-resources/run.sh
archetypes/alfresco-share-jar-archetype/src/main/resources/archetype-resources/run.bat
archetypes/alfresco-share-jar-archetype/src/main/resources/archetype-resources/run.sh
docs/getting-started.md

ACS-8405 Migrate to Docker Compose v2

---

plugins/alfresco-maven-plugin/pom.xml

https://hyland.atlassian.net/browse/PRODSEC-9150

[PRODSEC-9150] fix for snappy vulnerability

---

plugins/alfresco-maven-plugin/pom.xml

https://hyland.atlassian.net/browse/PRODSEC-8956

[PRODSEC-8956] fix for CVE Vulnerability SRCCLR-SID-22742 in commons-codec-1.11

---

.github/workflows/ci.yml
README.md
archetypes/alfresco-allinone-archetype/pom.xml
archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/README.md
archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/__rootArtifactId__-integration-tests/pom.xml
archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/__rootArtifactId__-platform/pom.xml
archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/__rootArtifactId__-share/pom.xml
archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/pom.xml
archetypes/alfresco-platform-jar-archetype/pom.xml
archetypes/alfresco-platform-jar-archetype/src/main/resources/archetype-resources/README.md
archetypes/alfresco-share-jar-archetype/pom.xml
archetypes/alfresco-share-jar-archetype/src/main/resources/archetype-resources/README.md
archetypes/archetypes-it/pom.xml
docs/README.md
docs/getting-started.md
docs/whats-new.md
docs/working-with-generated-projects/working-with-aio.md
modules/alfresco-rad/pom.xml
plugins/alfresco-maven-plugin/pom.xml
pom.xml

https://hyland.atlassian.net/browse/APPS-2991

[APPS-2991] Releasing Alfresco SDK 4.9.0

---

modules/alfresco-rad/pom.xml
pom.xml

https://hyland.atlassian.net/browse/APPS-3043

[APPS-3043] Upgrade to spring 6.1

---

.github/workflows/ci.yml
pom.xml

https://hyland.atlassian.net/browse/APPS-3094

[APPS-3094] remove 70 tests

---

plugins/alfresco-maven-plugin/pom.xml

https://hyland.atlassian.net/browse/PRODSEC-9642

[PRODSEC-9642] fix commons-io vulnerability

---

pom.xml

update nexus url

---

archetypes/alfresco-allinone-archetype/pom.xml
archetypes/alfresco-platform-jar-archetype/pom.xml
archetypes/alfresco-share-jar-archetype/pom.xml
archetypes/archetypes-it/pom.xml
modules/alfresco-rad/pom.xml
plugins/alfresco-maven-plugin/pom.xml
pom.xml

https://hyland.atlassian.net/browse/APPS-3219

[APPS-3219] Preparing for next development iteration

---

README.md
archetypes/alfresco-allinone-archetype/pom.xml
archetypes/alfresco-platform-jar-archetype/pom.xml
archetypes/alfresco-share-jar-archetype/pom.xml
archetypes/archetypes-it/pom.xml
docs/getting-started.md
modules/alfresco-rad/pom.xml
plugins/alfresco-maven-plugin/pom.xml
pom.xml

[APPS-3219] alfresco sdk 4.11.0 release

---

README.md

In this PR I have updated the Readme.md file and added the steps required to release sdk project to maven central

Added release steps in the readme
