archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/runner/tomcat/context-solr.xml
Changes SOLR's environment context variable values so that they use maven properties referencing home and data dir instead of assuming that SOLR data will always be inside project.
=> fix issue #317

archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/pom.xml
If you run archetype:generate with `-Dgoals=validate` (and this patch), then your generated project has an executable run.sh.
Best solution I could come up with.
=> make run.sh executable during the "validation" phase of the build

poms/alfresco-sdk-parent/pom.xml
Maven's "active by default" does behave intuitively.  If you turn on any other profiles, then the "active by default" ones are turned off.  
As a result, using the "enterprise" profile turns off "enforce-sdk-rules", which I believe was unintended.
I use a bit of a hack to fix this (looking for a non-existent file).  
From the maven docs:  "All profiles that are active by default are automatically deactivated when a profile in the POM is activated on the command line or through its activation config."
http://maven.apache.org/guides/introduction/introduction-to-profiles.html
=> change activation of enforce-sdk-rules so it's *really* on by default, as intended

archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/runner/pom.xml, poms/alfresco-sdk-parent/pom.xml
The current configuration doesn't encode url:s properly and this breaks any pages/webscripts that uses parameters that contains non us-ascii characters. Adding the uriEncoding solves this.
=> The current configuration doesn't encode url:s tomcat7-maven-plugin.

ISSUE_TEMPLATE.md
This commit provides an issue template which will be used when users will report a bug or suggest a new feature.
This should help to provide better and quicker support for the reported issues of alfresco SDK.
=> chore(github) : new github issue template

plugins/alfresco-maven-plugin/src/main/java/org/alfresco/maven/plugin/AbstractRunMojo.java
Default platform artifact ID seems to have changed in 93dde46 commit from "alfresco-platform" to "alfresco". Works until latest 201701 release of community as WARs are still available under "alfresco" artifactId. From 201702 community release there does not seem to be an alfresco.war artifact with artifactId "alfresco" and version 5.2.f, only available with artifactId "alfresco-platform".
=> Artifact ID fix for platform WAR

modules/alfresco-rad/src/main/resources/alfresco/extension/templates/webscripts/org/alfresco/rad/test/runtest.get.html.ftl, modules/alfresco-rad/src/main/resources/alfresco/extension/templates/webscripts/org/alfresco/rad/test/runtest.get.xml.ftl
See Issue https://github.com/Alfresco/alfresco-sdk/issues/478
A nullpointer in an Integration tests causes an error in Freemarker evaluation because the error message will be null and the template is not designed to handle this case. This could confuse the developer, because the integration test ends with an error like below, instead of a message about the nullpointer.
This is caused by the fact that message of JUnit's Failure class delegates to getMessage() of the throwable which can be null in some cases (Nullpointer for instance) causing the Freemarker template evaluation to fail which in turn hides the real problem in the integration test.
```
Caused by: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> failure.getMessage()  [in template …
```
=> Nullpointer in code crashes Freemarker evaluation within Integration Testing

plugins/alfresco-maven-plugin/src/main/java/org/alfresco/maven/plugin/AbstractRunMojo.java, plugins/alfresco-maven-plugin/src/main/java/org/alfresco/maven/plugin/RunMojo.java
Have a folder "src/test/resources/solr" in which you can put in custom solr configuration files, which will be automatically injected into "alf_data_dev/solr", so a developer can overwrite any files needed. If a developer doesn't need this feature he/she can simply leave that folder empty.
=> Feature request: adding support for custom solr config #474

modules/alfresco-rad/src/main/resources/alfresco/extension/templates/webscripts/org/alfresco/rad/test/runtest.get.xml.ftl
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```
We are having issues with assertEquals comparisons in integration tests. With the latest 3.0.2-SNAPSHOT the PR #477 was included to fix null pointer exceptions in the runtest.get.xml.ftl file. The PR fixed the null pointer errors but introduced new errors which come from the usage of using freemarker expressions ${test!""?html} where we would expect that the contents of the ftl variable test would first have a null check and then be html escaped. The observed behaviour however is that a null check is made but no html escape is made.
The correct freemarker expresson to use would be ${test!?html} or ${test!?xml} depending on the ftl type.
This PR fixes runtest.get.xml.ftl and should be …
=> Fix null check to work with assertEqual-failures and exception messages containing reserved xml characters

archetypes/alfresco-allinone-archetype/pom.xml, archetypes/alfresco-platform-jar-archetype/pom.xml, archetypes/alfresco-share-jar-archetype/pom.xml, modules/alfresco-rad/pom.xml, plugins/alfresco-maven-plugin/pom.xml, pom.xml
Bumping up the version number entries to 4.0.0 in all pom files.
Tests aren't running successfully afterwards, but they weren't on the SDK-4.0 branch neither. I assume more fixing is needed here.
=> Bump version to 4.0.0

README.md, archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/README.md, archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/__rootArtifactId__-platform-jar/pom.xml, archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/__rootArtifactId__-share-jar/pom.xml, archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/integration-tests/pom.xml, archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/pom.xml, archetypes/alfresco-platform-jar-archetype/src/main/resources/archetype-resources/pom.xml, archetypes/alfresco-share-jar-archetype/src/main/resources/archetype-resources/README.md, archetypes/alfresco-share-jar-archetype/src/main/resources/archetype-resources/pom.xml
The version number bump to 4.0 was still missing in some documentation files and some description elements.
=> Bumping version number to 4.0 for documentation + descriptions

modules/alfresco-rad/src/main/java/org/alfresco/rad/test/AlfrescoTestRunner.java
Modify the Alfresco RAD module to check for the java system property acs.endpoint.path
as an alternative for the default location of alfresco which is http://localhost:8080/alfresco.
This is useful to avoid connection refuse when starting ACS 6 as a container in a windows
machine with Docker Toolbox, which exposes the containers through a custom IP instead of
localhost.
=> Look for custom java system property for alfresco location

archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/run.bat, archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/run.sh, archetypes/alfresco-platform-jar-archetype/src/main/resources/archetype-resources/run.bat, archetypes/alfresco-platform-jar-archetype/src/main/resources/archetype-resources/run.sh, archetypes/alfresco-share-jar-archetype/src/main/resources/archetype-resources/run.bat, archetypes/alfresco-share-jar-archetype/src/main/resources/archetype-resources/run.sh, archetypes/archetypes-it/pom.xml, archetypes/archetypes-it/src/test/java/org/alfresco/maven/archetype/AbstractArchetypeIT.java, archetypes/archetypes-it/src/test/java/org/alfresco/maven/archetype/AllInOneArchetypeIT.java, archetypes/archetypes-it/src/test/java/org/alfresco/maven/archetype/PlatformJarArchetypeIT.java, archetypes/archetypes-it/src/test/java/org/alfresco/maven/archetype/ShareJarArchetypeIT.java
- Configure SLF4J in archetypes-it to show more detail in the console about the execution of the archetypes' integration tests.
- Change the bash/batch scripts to try to locate the `mvn` executable though the environment variable `M2_HOME`. If the variable is set, use it as `M2_HOME/bin/mvn`, if not simply use `mvn`.
=> Archetypes - Add IT logs

archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/__rootArtifactId__-platform-jar/src/main/assembly/amp.xml, archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/__rootArtifactId__-platform-jar/src/main/resources/alfresco/module/__artifactId__/log4j.properties, archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/__rootArtifactId__-share-jar/src/main/assembly/amp.xml, archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/__rootArtifactId__-share-jar/src/main/resources/alfresco/module/__rootArtifactId__-share-jar/log4j.properties, archetypes/alfresco-platform-jar-archetype/src/main/resources/archetype-resources/src/main/assembly/amp.xml, archetypes/alfresco-platform-jar-archetype/src/main/resources/archetype-resources/src/main/resources/alfresco/module/__artifactId__/log4j.properties, archetypes/alfresco-share-jar-archetype/src/main/resources/archetype-resources/src/main/assembly/amp.xml, archetypes/alfresco-share-jar-archetype/src/main/resources/archetype-resources/src/main/resources/alfresco/module/__artifactId__/log4j.properties
Add module-specific log4j.properties files to the archetypes and modify the assembly
files to include them in the AMPs. This way, it is possible to add custom log
configuration for each developed module.
#498
=> BUGFIX - 498 - Archetypes - Add module-specific log4j.properties to AMPs

plugins/alfresco-maven-plugin/src/main/java/org/alfresco/maven/plugin/AbstractRunMojo.java
Add a new parameter to the Alfresco Maven Plugin in order to be able to set the
Tomcat version to be executed when running Tomcat through the Tomcat Maven Plugin.
The parameter "tomcatVersion" (or the Maven property "maven.alfresco.tomcat.version")
allows to modify the default Tomcat version used by the Tomcat Maven Plugin. The
default version currently is 7.0.47 (set by the Tomcat Maven Plugin v2.2). If the version
of Tomcat is not set via the plugin parameter or the maven property, then the default
one is used.
https://github.com/Alfresco/alfresco-sdk/issues/499
=> BUGFIX - 499 - Maven Plugin - Add the ability to set Tomcat version

plugins/alfresco-maven-plugin/pom.xml, plugins/alfresco-maven-plugin/src/main/java/org/alfresco/maven/plugin/AbstractRunMojo.java
Ensure the unmount of the war files in the alfresco maven plugin to avoid
the exception thrown by the FsSyncShutdownHook.
=> BUGFIX - MNT-19097 - Ensure unmount war files

plugins/alfresco-maven-plugin/src/main/java/org/alfresco/maven/plugin/AbstractRunMojo.java
Solr4 indexes transactions every 15 seconds by default and it is currently not customizable in the SDK.
In SDK 2 it was possible to use lucene as a search system during integration tests, and indexing was then almost imediate. 
While migrating some projects to the SDK 3, we had to modify many tests to wait 16 seconds before executing methods which perform a search.
It makes the execution of all tests very long. For this reason we'd like the indexation frequency (property **alfresco.cron** in solrcore.properties) to be customizable so that we can set it to 5 seconds for example.
=> Make the Solr indexation frequency customizable

modules/alfresco-rad/src/main/java/org/alfresco/rad/test/AlfrescoTestRunner.java
We asume we are in the following case where we have an abstract class which declares some test methods :
```
@RunWith(AlfrescoTestRunner.class)
public abstract class AbstractIT {
@Test    
public void test() {
doSomeThing(abstractMethod());
}
abstract protected Object abstractMethod();
...
}
```
And several test classes extending the abstract class above, and which are run during integration-test phase :
```
public class ChildIT extends AbstractIT {
@Override
protected Object abstractMethod() {
...
}
}
```
Currently, when the AlfrescoTestRunner builds the name of the test methods to be run before sending it to the RunTestWebscript, it resolves the class name by getting the declaringClass of the test method, which is "AbstractIT" in our case.
So in our case, the RunTestWebscript will …
=> BUGFIX - Allow to write test methods in abstract classes

plugins/alfresco-maven-plugin/src/main/java/org/alfresco/maven/plugin/AbstractRunMojo.java
Code change migrated from PR https://github.com/Alfresco/alfresco-sdk/pull/431.
Change implemented by the user @pzrinscak.
Modify the Alfresco Maven Plugin to add the possibility to set
a custom Tomcat context file for the platform war. This features
enables the possibility to define custom JNDI resources in the
context of the Alfresco platform application.
#425
=> BUGFIX - 425 - Maven Plugin - Support for platform context file

plugins/alfresco-maven-plugin/src/main/java/org/alfresco/maven/plugin/BuildWarsMojo.java
Add a new goal to the Alfresco Maven Plugin to be able to generate the WAR files (platform, share and/or activity if they're enabled) without the need of running the Tomcat server.
#420
=> BUGFIX - 420 - Maven Plugin - Add goal to generate WARs only

docs/advanced-topics/amps.md
Fix the documentation about installing 3rd party AMPs because they must be added as a dependency in the docker module and not in the jar module.
#526
=> BUGFIX - 526 - Documentation - Installing 3rd party AMPs

plugins/alfresco-maven-plugin/src/main/java/org/alfresco/maven/plugin/AbstractRunMojo.java
Add a new parameter (`tomcatMavenPluginVersion`) and maven property
(`maven.alfresco.tomcat.maven.plugin.version`) to be able to set the version of
the Tomcat Maven Plugin that is going to be used in the Alfresco Maven
Plugin to run the project.
This way, an integrator can create a patched version of the Tomcat Plugin to
solve any issue with it and tell the Alfresco Maven Plugin to use that fixed
version of the Tomcat Plugin. This is helpful with the reported issue about
the `maxHttpHeaderSize` (https://github.com/Alfresco/alfresco-sdk/issues/440).
#440
=> BUGFIX - 440 - Maven Plugin - Make Tomcat Maven Plugin version configurable

archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/integration-tests/src/test/java/platformsample/DemoComponentIT.java
Modity the assertion about the name of the company home node in the
integration test DemoComponentIT to avoid issues with the language
in which the Alfresco environment is installed. It asserts now
about the path of the node which is independant from the language
of the application.
#457
=> BUGFIX - 457 - Archetypes - Modify IT company home assertion

docs/README.md, docs/advanced-topics/switching-dbs.md
Add a new article to explain how to switch from the default PostgreSQL database to another one (MySQL).
=> Documentation - Switching ACS database

archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/__rootArtifactId__-platform-docker/pom.xml, archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/__rootArtifactId__-share-docker/pom.xml
Modify the AIO archetype docker modules to remove the redundant copy of the dependency to the corresponding jar module (share or platform).
#539
=> Archetypes - Remove redundant dependency copy

archetypes/alfresco-platform-jar-archetype/src/main/resources/archetype-resources/pom.xml, archetypes/alfresco-share-jar-archetype/src/main/resources/archetype-resources/pom.xml
Change the module dependency version to `${project.version}` to avoid issues updating the project version and forgetting the update in the dependencies.
Created from PR https://github.com/Alfresco/alfresco-sdk/pull/550 to apply it to the last version of the archetype (it includes new tests dependency in the platform module).
Thanks @douglascrp !
#548 #549
=> Archetypes - Update module dependency version

archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/README.md, archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/run.bat, archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/run.sh, docs/advanced-topics/integration-testing/it-running.md, docs/working-with-generated-projects/README.md
Modify the run scripts to add the task: `build_start_it_supported`. 
After the last changes regarding the way the project is compiled and retrieves the IT dependencies, it lost the ability to run the project in docker with IT support (including the libraries required to execute IT) but without executing the tests. It only had `build_start` (no IT supported) and `build_test` (IT supported but started and stopped the environment after IT execution).
This new task allows the execution of the docker environment with IT execution supported to cover the next use cases:
- Running IT classes from IDE (for instance, to debug the execution).
- Running IT classes with hot reload enabled.
=> Archetypes - Add build with IT supported task

archetypes/alfresco-share-jar-archetype/src/main/resources/archetype-resources/docker/docker-compose.yml
Modify the `docker-compose.yml` file of the share-jar archetype in order to comment out the unnecessary containers (ACS, ASS, DB). They're optional and can be used simply removing the comments.
Created from https://github.com/Alfresco/alfresco-sdk/pull/552 to solve the conflicts. 
Thanks @douglascrp!
#551
=> Archetypes - Make ACS containers optional in share archetype

docs/advanced-topics/switching-versions.md, docs/advanced-topics/working-with-enterprise/README.md, modules/alfresco-rad/pom.xml, pom.xml
Update Alfresco 6.1 version numbers.
**Community**
* ACS - 6.1.2-ga
* Share - 6.1.0-RC3
**Enterprise**
* ACS - 6.1.0
* Share - 6.1.0
=> Archetypes - Update Alfresco 6.1 versions

archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/run.bat, archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/run.sh
Add the compilation of the IT maven module to the reload_acs script task to avoid a compilation failure if this module is not compiled in this task.
=> Archetypes - Compile IT module to avoid fail reload ACS

archetypes/alfresco-platform-jar-archetype/src/main/resources/archetype-resources/README.md, archetypes/alfresco-platform-jar-archetype/src/main/resources/archetype-resources/pom.xml, archetypes/alfresco-platform-jar-archetype/src/main/resources/archetype-resources/run.bat, archetypes/alfresco-platform-jar-archetype/src/main/resources/archetype-resources/run.sh, docs/advanced-topics/amps.md
- Build the project using package goal instead of install
- Copy the test dependencies only when IT is executed
- Add the build_start_it_supported task to execution scripts
=> Archetypes - Change platform archetype build approach

archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/__rootArtifactId__-platform-docker/src/main/docker/Dockerfile, archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/__rootArtifactId__-platform-docker/src/main/docker/alfresco-global.properties, archetypes/alfresco-platform-jar-archetype/src/main/resources/archetype-resources/src/main/docker/Dockerfile, archetypes/alfresco-platform-jar-archetype/src/main/resources/archetype-resources/src/main/docker/alfresco-global.properties, archetypes/alfresco-share-jar-archetype/src/main/resources/archetype-resources/docker/docker-compose.yml, pom.xml
- New alfresco community and enterprise 6.2.0 profiles
- Execute dockerfile as root to avoid issues applying AMPs
- Disable transformation service by default in archetypes
=> Archetypes - Add support for ACS 6.2

archetypes/alfresco-platform-jar-archetype/src/main/resources/archetype-resources/pom.xml, archetypes/alfresco-share-jar-archetype/src/main/resources/archetype-resources/pom.xml, docs/advanced-topics/amps.md
Fix the use of the deprecated maven key ${build.finalName}. Using ${project.build.finalName}
instead.
=> Archetypes - Fix deprecated use of maven project name

pom.xml
This PR requires these artefacts to be available:
* acs-community-packaging: 7.0.2, 7.1.2, 7.2.1
* acs-packaging: 7.02, 7.1.2, 7.2.1
=> MNT-22946: version bump of acs-*-packaging and share

pom.xml
The purpose of this PR is to fix an error that occurs when we try to build a project using the alfresco-share-jar-archetype. Inlining the keystore settings prevents those lines from not being commented out and thus not resulting in an invalid docker-compose file 
[https://alfresco.atlassian.net/browse/MNT-22384](https://alfresco.atlassian.net/browse/MNT-22384)
[Edit] The problem initially occurs because of this commented out line in the docker-compose template for the share jar archetype `# ${symbol_dollar}{keystore.settings}` which then gets replaced by the value of keystore settings in the `pom.xml` file. What ends up happening is only the first of those settings is put in a comment and so that results in an invalid yaml file
=> MNT-22384: Inline keystore settings to avoid invalid docker-compose file

pom.xml
https://hyland.atlassian.net/browse/APPS-3205
Due to Quiklink issue the older versions of community repo(**23.4.0 & 23.3.0**) is removed. Following new version is released
**(23.4.1 & 23.3.3)**. So this needs to updated here.
=> [APPS-3205] Update community version from 23.4.0 & 23.3.0 to 23.4.1 & 23.3.3

archetypes/alfresco-allinone-archetype/src/main/resources/archetype-resources/docker/docker-compose.yml, archetypes/alfresco-platform-jar-archetype/src/main/resources/archetype-resources/docker/docker-compose.yml
The root cause of the issue is that when generating a project using Alfresco SDK 4.11.0, Maven downloads the project archetype (such as the AIO module) from Nexus. This archetype is packaged as a JAR file and contains a predefined docker-compose.yml file. Unfortunately, this file includes outdated Docker image versions that are no longer recommended for ACS 25.1.
To resolve this,
1. Updated the docker-compose.yml file in the SDK source repository to include the latest supported Docker image versions (as per the Supported Platforms documentation).
2. Raised a pull request (PR) with these updates.
Once this PR is merged, a new SDK version will be released. This new version will include the updated archetype JAR.
=> [MNT-25067]: AIO and Alfresco platform docker compose file update with new version
